version: "3"

services:
  telegram-bot:
    container_name: telegram-bot
    build: .

    environment:
      STB_BOT_TOKEN: ${STB_BOT_TOKEN}
      STB_REDIS_ENABLED: ${STB_REDIS_ENABLED}
      STB_REDIS_IP: redis-server

    volumes:
      - ${PWD}/data/files/imagenet-vgg-verydeep-19.mat:/opt/tg/models/pretrained/imagenet-vgg-verydeep-19.mat
      - ${PWD}/data/files/decoder_epoch_20.pth:/opt/tg/DeepPhotoStyle_pytorch/seg_checkpoint/decoder_epoch_20.pth
      - ${PWD}/data/files/encoder_epoch_20.pth:/opt/tg/DeepPhotoStyle_pytorch/seg_checkpoint/encoder_epoch_20.pth

    depends_on:
      - redis-server

  redis-server:
    container_name: redis-server
    image: redis

    ports:
    - "6379:6379"

    volumes:
      - redis-data:/data

volumes:
  redis-data:
